require 'minitest/spec'
require 'minitest/autorun'
require 'wechat_pay'
require 'fakeweb'

WechatPay.app_id = 'app_id'
WechatPay.app_secret = 'app_secret'
WechatPay.pay_sign_key = 'pay_sign_key'
WechatPay.partner_id = 'partner_id'
WechatPay.partner_key = 'partner_key'
